name: flutter_overlay_window_example
description: Demonstrates how to use the flutter_overlay_window plugin.

publish_to: 'none'

environment:
  sdk: ">=2.16.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  multiavatar: ^0.1.5
  provider: ^6.0.2
  rename: ^2.0.0-dev.2
  shimmer: ^2.0.0
  simple_animations: ^4.0.2
  supercharged: ^2.1.1
  flutter_accessibility_service: ^0.2.2
  flutter_overlay_window: ^0.4.4
  cupertino_icons: ^1.0.2
  flutter_tts: ^4.0.2
  sqflite: ^2.3.2
  restart_app: ^1.2.1
  audioplayers: ^6.0.0
  path_provider: ^2.1.3
  
dev_dependencies:
  flutter_lints: ^1.0.0
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true
  assets:
    - assets/wallpaper2.jpg
    - assets/alternate_logo.png
    - assets/selfeggio_174_trimmed.wav
    - assets/selfeggio_396_trimmed.wav
    - assets/selfeggio_285_trimmed.wav
    - assets/selfeggio_285_trimmed.wav
    - assets/selfeggio_528_trimmed.wav
    - assets/selfeggio_639_trimmed.wav
    - assets/selfeggio_741_trimmed.wav
    - assets/selfeggio_852_trimmed.wav
    - assets/selfeggio_963_trimmed.wav
    - assets/bonus_432Hz_trimmed.mp3
    - assets/3rd_eye_development.jpeg

flutter_launcher_icons:
  android: "launcher_icon"
  image_path: "assets/icons/icon.png"
  # TO DO: Add launcher logic for IOS here later on.
  min_sdk_android: 21
  remove_alpha_ios: true


